from __future__ import annotations

from .coordinate import Angstrom, mk_angstrom
from .molecule import AtomicSymbol, ElementAttributes
from . import orbital


def normalize_symbols(symbol_a: AtomicSymbol, symbol_b: AtomicSymbol) -> tuple[AtomicSymbol, AtomicSymbol]:
    return (symbol_a, symbol_b) if symbol_a.value <= symbol_b.value else (symbol_b, symbol_a)


_BOND_LENGTHS: dict[tuple[int, AtomicSymbol, AtomicSymbol], Angstrom] = {
    (1, AtomicSymbol.H, AtomicSymbol.H): mk_angstrom(0.74),
    (1, AtomicSymbol.H, AtomicSymbol.C): mk_angstrom(1.09),
    (1, AtomicSymbol.H, AtomicSymbol.N): mk_angstrom(1.01),
    (1, AtomicSymbol.H, AtomicSymbol.O): mk_angstrom(0.96),
    (1, AtomicSymbol.H, AtomicSymbol.Fe): mk_angstrom(1.52),
    (1, AtomicSymbol.H, AtomicSymbol.B): mk_angstrom(1.19),
    (1, AtomicSymbol.C, AtomicSymbol.C): mk_angstrom(1.54),
    (1, AtomicSymbol.C, AtomicSymbol.N): mk_angstrom(1.47),
    (1, AtomicSymbol.C, AtomicSymbol.O): mk_angstrom(1.43),
    (1, AtomicSymbol.C, AtomicSymbol.Fe): mk_angstrom(1.84),
    (1, AtomicSymbol.C, AtomicSymbol.B): mk_angstrom(1.55),
    (1, AtomicSymbol.N, AtomicSymbol.N): mk_angstrom(1.45),
    (1, AtomicSymbol.N, AtomicSymbol.O): mk_angstrom(1.40),
    (1, AtomicSymbol.N, AtomicSymbol.Fe): mk_angstrom(1.76),
    (1, AtomicSymbol.N, AtomicSymbol.B): mk_angstrom(1.55),
    (1, AtomicSymbol.O, AtomicSymbol.O): mk_angstrom(1.48),
    (1, AtomicSymbol.O, AtomicSymbol.Fe): mk_angstrom(1.70),
    (1, AtomicSymbol.O, AtomicSymbol.B): mk_angstrom(1.49),
    (1, AtomicSymbol.Fe, AtomicSymbol.Fe): mk_angstrom(2.48),
    (1, AtomicSymbol.Fe, AtomicSymbol.B): mk_angstrom(2.03),
    (1, AtomicSymbol.B, AtomicSymbol.B): mk_angstrom(1.59),
    (2, AtomicSymbol.H, AtomicSymbol.H): mk_angstrom(0.74),
    (2, AtomicSymbol.H, AtomicSymbol.C): mk_angstrom(1.06),
    (2, AtomicSymbol.H, AtomicSymbol.N): mk_angstrom(1.01),
    (2, AtomicSymbol.H, AtomicSymbol.O): mk_angstrom(0.96),
    (2, AtomicSymbol.H, AtomicSymbol.Fe): mk_angstrom(1.52),
    (2, AtomicSymbol.H, AtomicSymbol.B): mk_angstrom(1.19),
    (2, AtomicSymbol.C, AtomicSymbol.C): mk_angstrom(1.34),
    (2, AtomicSymbol.C, AtomicSymbol.N): mk_angstrom(1.27),
    (2, AtomicSymbol.C, AtomicSymbol.O): mk_angstrom(1.20),
    (2, AtomicSymbol.C, AtomicSymbol.Fe): mk_angstrom(1.64),
    (2, AtomicSymbol.C, AtomicSymbol.B): mk_angstrom(1.37),
    (2, AtomicSymbol.N, AtomicSymbol.N): mk_angstrom(1.25),
    (2, AtomicSymbol.N, AtomicSymbol.O): mk_angstrom(1.20),
    (2, AtomicSymbol.N, AtomicSymbol.Fe): mk_angstrom(1.64),
    (2, AtomicSymbol.N, AtomicSymbol.B): mk_angstrom(1.33),
    (2, AtomicSymbol.O, AtomicSymbol.O): mk_angstrom(1.21),
    (2, AtomicSymbol.O, AtomicSymbol.Fe): mk_angstrom(1.58),
    (2, AtomicSymbol.O, AtomicSymbol.B): mk_angstrom(1.26),
    (2, AtomicSymbol.Fe, AtomicSymbol.Fe): mk_angstrom(2.26),
    (2, AtomicSymbol.Fe, AtomicSymbol.B): mk_angstrom(1.89),
    (2, AtomicSymbol.B, AtomicSymbol.B): mk_angstrom(1.59),
    (3, AtomicSymbol.H, AtomicSymbol.H): mk_angstrom(0.74),
    (3, AtomicSymbol.H, AtomicSymbol.C): mk_angstrom(1.06),
    (3, AtomicSymbol.H, AtomicSymbol.N): mk_angstrom(1.01),
    (3, AtomicSymbol.H, AtomicSymbol.O): mk_angstrom(0.96),
    (3, AtomicSymbol.H, AtomicSymbol.Fe): mk_angstrom(1.52),
    (3, AtomicSymbol.H, AtomicSymbol.B): mk_angstrom(1.19),
    (3, AtomicSymbol.C, AtomicSymbol.C): mk_angstrom(1.20),
    (3, AtomicSymbol.C, AtomicSymbol.N): mk_angstrom(1.14),
    (3, AtomicSymbol.C, AtomicSymbol.O): mk_angstrom(1.13),
    (3, AtomicSymbol.C, AtomicSymbol.Fe): mk_angstrom(1.44),
    (3, AtomicSymbol.C, AtomicSymbol.B): mk_angstrom(1.19),
    (3, AtomicSymbol.N, AtomicSymbol.N): mk_angstrom(1.10),
    (3, AtomicSymbol.N, AtomicSymbol.O): mk_angstrom(1.06),
    (3, AtomicSymbol.N, AtomicSymbol.Fe): mk_angstrom(1.50),
    (3, AtomicSymbol.N, AtomicSymbol.B): mk_angstrom(1.20),
    (3, AtomicSymbol.O, AtomicSymbol.O): mk_angstrom(1.21),
    (3, AtomicSymbol.O, AtomicSymbol.Fe): mk_angstrom(1.58),
    (3, AtomicSymbol.O, AtomicSymbol.B): mk_angstrom(1.20),
    (3, AtomicSymbol.Fe, AtomicSymbol.Fe): mk_angstrom(2.26),
    (3, AtomicSymbol.Fe, AtomicSymbol.B): mk_angstrom(1.89),
    (3, AtomicSymbol.B, AtomicSymbol.B): mk_angstrom(1.59),
}


_NOMINAL_VALENCE: dict[AtomicSymbol, tuple[int, int]] = {
    AtomicSymbol.H: (2, 2),
    AtomicSymbol.C: (8, 10),
    AtomicSymbol.N: (6, 6),
    AtomicSymbol.O: (4, 4),
    AtomicSymbol.F: (2, 2),
    AtomicSymbol.P: (6, 10),
    AtomicSymbol.Si: (8, 8),
    AtomicSymbol.S: (4, 12),
    AtomicSymbol.Cl: (2, 2),
    AtomicSymbol.Br: (2, 2),
    AtomicSymbol.B: (6, 8),
    AtomicSymbol.Fe: (0, 12),
    AtomicSymbol.I: (2, 2),
    AtomicSymbol.Na: (2, 2),
}

# Atomic weights use CIAAW 2024 standard atomic weights where a standard value
# exists. Radioactive elements without a standard atomic weight use NIST SP 966
# June 2024 mass numbers for the longest-lived isotope.
ALL_ATOMIC_SYMBOLS: tuple[AtomicSymbol, ...] = (
    AtomicSymbol.H,
    AtomicSymbol.He,
    AtomicSymbol.Li,
    AtomicSymbol.Be,
    AtomicSymbol.B,
    AtomicSymbol.C,
    AtomicSymbol.N,
    AtomicSymbol.O,
    AtomicSymbol.F,
    AtomicSymbol.Ne,
    AtomicSymbol.Na,
    AtomicSymbol.Mg,
    AtomicSymbol.Al,
    AtomicSymbol.Si,
    AtomicSymbol.P,
    AtomicSymbol.S,
    AtomicSymbol.Cl,
    AtomicSymbol.Ar,
    AtomicSymbol.K,
    AtomicSymbol.Ca,
    AtomicSymbol.Sc,
    AtomicSymbol.Ti,
    AtomicSymbol.V,
    AtomicSymbol.Cr,
    AtomicSymbol.Mn,
    AtomicSymbol.Fe,
    AtomicSymbol.Co,
    AtomicSymbol.Ni,
    AtomicSymbol.Cu,
    AtomicSymbol.Zn,
    AtomicSymbol.Ga,
    AtomicSymbol.Ge,
    AtomicSymbol.As,
    AtomicSymbol.Se,
    AtomicSymbol.Br,
    AtomicSymbol.Kr,
    AtomicSymbol.Rb,
    AtomicSymbol.Sr,
    AtomicSymbol.Y,
    AtomicSymbol.Zr,
    AtomicSymbol.Nb,
    AtomicSymbol.Mo,
    AtomicSymbol.Tc,
    AtomicSymbol.Ru,
    AtomicSymbol.Rh,
    AtomicSymbol.Pd,
    AtomicSymbol.Ag,
    AtomicSymbol.Cd,
    AtomicSymbol.In,
    AtomicSymbol.Sn,
    AtomicSymbol.Sb,
    AtomicSymbol.Te,
    AtomicSymbol.I,
    AtomicSymbol.Xe,
    AtomicSymbol.Cs,
    AtomicSymbol.Ba,
    AtomicSymbol.La,
    AtomicSymbol.Ce,
    AtomicSymbol.Pr,
    AtomicSymbol.Nd,
    AtomicSymbol.Pm,
    AtomicSymbol.Sm,
    AtomicSymbol.Eu,
    AtomicSymbol.Gd,
    AtomicSymbol.Tb,
    AtomicSymbol.Dy,
    AtomicSymbol.Ho,
    AtomicSymbol.Er,
    AtomicSymbol.Tm,
    AtomicSymbol.Yb,
    AtomicSymbol.Lu,
    AtomicSymbol.Hf,
    AtomicSymbol.Ta,
    AtomicSymbol.W,
    AtomicSymbol.Re,
    AtomicSymbol.Os,
    AtomicSymbol.Ir,
    AtomicSymbol.Pt,
    AtomicSymbol.Au,
    AtomicSymbol.Hg,
    AtomicSymbol.Tl,
    AtomicSymbol.Pb,
    AtomicSymbol.Bi,
    AtomicSymbol.Po,
    AtomicSymbol.At,
    AtomicSymbol.Rn,
    AtomicSymbol.Fr,
    AtomicSymbol.Ra,
    AtomicSymbol.Ac,
    AtomicSymbol.Th,
    AtomicSymbol.Pa,
    AtomicSymbol.U,
    AtomicSymbol.Np,
    AtomicSymbol.Pu,
    AtomicSymbol.Am,
    AtomicSymbol.Cm,
    AtomicSymbol.Bk,
    AtomicSymbol.Cf,
    AtomicSymbol.Es,
    AtomicSymbol.Fm,
    AtomicSymbol.Md,
    AtomicSymbol.No,
    AtomicSymbol.Lr,
    AtomicSymbol.Rf,
    AtomicSymbol.Db,
    AtomicSymbol.Sg,
    AtomicSymbol.Bh,
    AtomicSymbol.Hs,
    AtomicSymbol.Mt,
    AtomicSymbol.Ds,
    AtomicSymbol.Rg,
    AtomicSymbol.Cn,
    AtomicSymbol.Nh,
    AtomicSymbol.Fl,
    AtomicSymbol.Mc,
    AtomicSymbol.Lv,
    AtomicSymbol.Ts,
    AtomicSymbol.Og,
)

_ELEMENT_DATA: dict[AtomicSymbol, tuple[int, float]] = {
    AtomicSymbol.H: (1, 1.008),
    AtomicSymbol.He: (2, 4.002602),
    AtomicSymbol.Li: (3, 6.94),
    AtomicSymbol.Be: (4, 9.0121831),
    AtomicSymbol.B: (5, 10.81),
    AtomicSymbol.C: (6, 12.011),
    AtomicSymbol.N: (7, 14.007),
    AtomicSymbol.O: (8, 15.999),
    AtomicSymbol.F: (9, 18.998403162),
    AtomicSymbol.Ne: (10, 20.1797),
    AtomicSymbol.Na: (11, 22.98976928),
    AtomicSymbol.Mg: (12, 24.305),
    AtomicSymbol.Al: (13, 26.9815384),
    AtomicSymbol.Si: (14, 28.085),
    AtomicSymbol.P: (15, 30.973761998),
    AtomicSymbol.S: (16, 32.06),
    AtomicSymbol.Cl: (17, 35.45),
    AtomicSymbol.Ar: (18, 39.95),
    AtomicSymbol.K: (19, 39.0983),
    AtomicSymbol.Ca: (20, 40.078),
    AtomicSymbol.Sc: (21, 44.955907),
    AtomicSymbol.Ti: (22, 47.867),
    AtomicSymbol.V: (23, 50.9415),
    AtomicSymbol.Cr: (24, 51.9961),
    AtomicSymbol.Mn: (25, 54.938043),
    AtomicSymbol.Fe: (26, 55.845),
    AtomicSymbol.Co: (27, 58.933194),
    AtomicSymbol.Ni: (28, 58.6934),
    AtomicSymbol.Cu: (29, 63.546),
    AtomicSymbol.Zn: (30, 65.38),
    AtomicSymbol.Ga: (31, 69.723),
    AtomicSymbol.Ge: (32, 72.630),
    AtomicSymbol.As: (33, 74.921595),
    AtomicSymbol.Se: (34, 78.971),
    AtomicSymbol.Br: (35, 79.904),
    AtomicSymbol.Kr: (36, 83.798),
    AtomicSymbol.Rb: (37, 85.4678),
    AtomicSymbol.Sr: (38, 87.62),
    AtomicSymbol.Y: (39, 88.905838),
    AtomicSymbol.Zr: (40, 91.222),
    AtomicSymbol.Nb: (41, 92.90637),
    AtomicSymbol.Mo: (42, 95.95),
    AtomicSymbol.Tc: (43, 97.0),
    AtomicSymbol.Ru: (44, 101.07),
    AtomicSymbol.Rh: (45, 102.90549),
    AtomicSymbol.Pd: (46, 106.42),
    AtomicSymbol.Ag: (47, 107.8682),
    AtomicSymbol.Cd: (48, 112.414),
    AtomicSymbol.In: (49, 114.818),
    AtomicSymbol.Sn: (50, 118.710),
    AtomicSymbol.Sb: (51, 121.760),
    AtomicSymbol.Te: (52, 127.60),
    AtomicSymbol.I: (53, 126.90447),
    AtomicSymbol.Xe: (54, 131.293),
    AtomicSymbol.Cs: (55, 132.90545196),
    AtomicSymbol.Ba: (56, 137.327),
    AtomicSymbol.La: (57, 138.90547),
    AtomicSymbol.Ce: (58, 140.116),
    AtomicSymbol.Pr: (59, 140.90766),
    AtomicSymbol.Nd: (60, 144.242),
    AtomicSymbol.Pm: (61, 145.0),
    AtomicSymbol.Sm: (62, 150.36),
    AtomicSymbol.Eu: (63, 151.964),
    AtomicSymbol.Gd: (64, 157.249),
    AtomicSymbol.Tb: (65, 158.925354),
    AtomicSymbol.Dy: (66, 162.500),
    AtomicSymbol.Ho: (67, 164.930329),
    AtomicSymbol.Er: (68, 167.259),
    AtomicSymbol.Tm: (69, 168.934219),
    AtomicSymbol.Yb: (70, 173.045),
    AtomicSymbol.Lu: (71, 174.96669),
    AtomicSymbol.Hf: (72, 178.486),
    AtomicSymbol.Ta: (73, 180.94788),
    AtomicSymbol.W: (74, 183.84),
    AtomicSymbol.Re: (75, 186.207),
    AtomicSymbol.Os: (76, 190.23),
    AtomicSymbol.Ir: (77, 192.217),
    AtomicSymbol.Pt: (78, 195.084),
    AtomicSymbol.Au: (79, 196.966570),
    AtomicSymbol.Hg: (80, 200.592),
    AtomicSymbol.Tl: (81, 204.38),
    AtomicSymbol.Pb: (82, 207.2),
    AtomicSymbol.Bi: (83, 208.98040),
    AtomicSymbol.Po: (84, 209.0),
    AtomicSymbol.At: (85, 210.0),
    AtomicSymbol.Rn: (86, 222.0),
    AtomicSymbol.Fr: (87, 223.0),
    AtomicSymbol.Ra: (88, 226.0),
    AtomicSymbol.Ac: (89, 227.0),
    AtomicSymbol.Th: (90, 232.0377),
    AtomicSymbol.Pa: (91, 231.03588),
    AtomicSymbol.U: (92, 238.02891),
    AtomicSymbol.Np: (93, 237.0),
    AtomicSymbol.Pu: (94, 244.0),
    AtomicSymbol.Am: (95, 243.0),
    AtomicSymbol.Cm: (96, 247.0),
    AtomicSymbol.Bk: (97, 247.0),
    AtomicSymbol.Cf: (98, 251.0),
    AtomicSymbol.Es: (99, 252.0),
    AtomicSymbol.Fm: (100, 257.0),
    AtomicSymbol.Md: (101, 258.0),
    AtomicSymbol.No: (102, 259.0),
    AtomicSymbol.Lr: (103, 262.0),
    AtomicSymbol.Rf: (104, 267.0),
    AtomicSymbol.Db: (105, 268.0),
    AtomicSymbol.Sg: (106, 269.0),
    AtomicSymbol.Bh: (107, 270.0),
    AtomicSymbol.Hs: (108, 269.0),
    AtomicSymbol.Mt: (109, 277.0),
    AtomicSymbol.Ds: (110, 281.0),
    AtomicSymbol.Rg: (111, 282.0),
    AtomicSymbol.Cn: (112, 285.0),
    AtomicSymbol.Nh: (113, 286.0),
    AtomicSymbol.Fl: (114, 290.0),
    AtomicSymbol.Mc: (115, 290.0),
    AtomicSymbol.Lv: (116, 293.0),
    AtomicSymbol.Ts: (117, 294.0),
    AtomicSymbol.Og: (118, 294.0),
}


_ELEMENT_SHELLS = {
    AtomicSymbol.O: orbital.OXYGEN,
    AtomicSymbol.H: orbital.HYDROGEN,
    AtomicSymbol.N: orbital.NITROGEN,
    AtomicSymbol.C: orbital.CARBON,
    AtomicSymbol.B: orbital.BORON,
    AtomicSymbol.Fe: orbital.IRON,
    AtomicSymbol.F: orbital.FLUORINE,
    AtomicSymbol.Cl: orbital.CHLORINE,
    AtomicSymbol.S: orbital.SULFUR,
    AtomicSymbol.Br: orbital.BROMINE,
    AtomicSymbol.P: orbital.PHOSPHORUS,
    AtomicSymbol.Si: orbital.SILICON,
    AtomicSymbol.I: orbital.IODINE,
    AtomicSymbol.Na: orbital.SODIUM,
}


_ELEMENT_ATTRIBUTES: dict[AtomicSymbol, ElementAttributes] = {
    symbol: ElementAttributes(symbol, atomic_number, atomic_weight, _ELEMENT_SHELLS.get(symbol))
    for symbol, (atomic_number, atomic_weight) in _ELEMENT_DATA.items()
}

if set(ALL_ATOMIC_SYMBOLS) != set(AtomicSymbol) or set(_ELEMENT_DATA) != set(AtomicSymbol):
    raise RuntimeError("Atomic symbol table and element data table are out of sync")


def equilibrium_bond_length(
    bond_order: int,
    symbol_a: AtomicSymbol,
    symbol_b: AtomicSymbol,
) -> Angstrom | None:
    normalized = normalize_symbols(symbol_a, symbol_b)
    return _BOND_LENGTHS.get((bond_order, normalized[0], normalized[1]))


def nominal_valence(symbol: AtomicSymbol) -> tuple[int, int]:
    return _NOMINAL_VALENCE.get(symbol, (0, 16))


def get_max_bonds_symbol(symbol: AtomicSymbol) -> float:
    _, max_electrons = nominal_valence(symbol)
    return max_electrons / 2.0


def element_attributes(symbol: AtomicSymbol) -> ElementAttributes:
    return _ELEMENT_ATTRIBUTES[symbol]
